paths:
  mimic_dir: &mimic_dir datasets/mimic3/csv
  static_dir: &static_dir datasets/mimic3/static
  dataset_dir: &dataset_dir datasets/mimic3_50_old_transicd
  word2vec_dir: &word2vec_dir datasets/mimic3_50_old_transicd/word2vec
  output_dir: &output_dir results/transicd_mimic3_50_old

demo:
  icd_desc_file: datasets/mimic3/static/icd9_descriptions.txt
  min_input_len: 4
  top_k: 10
  use_gpu: true

clinical_note_preprocessing:
  to_lower:
    perform: true
  remove_punctuation:
    perform: true
  remove_numeric:
    perform: true
    replace_numerics_with_letter: "n"
  remove_stopwords:
    perform: true
    params:
      stopwords_file_path: null
      remove_common_medical_terms: true
  stem_or_lemmatize:
    perform: true
    params:
      stemmer_name: nltk.SnowballStemmer
  truncate:
    perform: false

dataset:
  name: base_dataset
  params:
    dataset_dir: *dataset_dir
    word2vec_dir: *word2vec_dir
    pad_token: "<pad>"
    unk_token: "<unk>"
    max_length: 2500
    label_file: labels.json
    data_file: test.json  # not used

model:
  name: transicd
  params:
    num_classes: 50
    max_len: 2500
    pad_idx: 0
    # Embedding Layer params
    embed_dir: *word2vec_dir
    freeze_embedding_layer: true
    # Transformer Layer params
    num_layers: 2
    num_heads: 8
    transformer_ff_up_scale_factor_for_hidden_dim: 4
    dropout: 0.1
    # Label Attention Layer params
    attn_expansion: 2
  embed_layer_name: "word_embedding_layer"

checkpoint_saver:
  name: base_saver
  params:
    checkpoint_dir: *output_dir
    interval: 1
    max_to_keep: 5
    ckpt_fname_format: "ckpt-{}.pth"
    best_fname_format: "best-{}.pth"
    metric:
      name: prec_at_8
      class: prec_at_k
      params:
        k: 8
    desired: max
